### ISSUE TITLE
Uncaught TypeError: Illegal offset type in line 156 of usu.php

### ISSUE THREAD

**Issue by ser** [phpbb-seo/usu#47]
version 2.0.2 = current github master 

PHPBB 3.3.4 / PHP8 / MySQL8 / PHP_FCGI / NGINX

clicking on PHPBB SEO tab in ACP gives 500:

```
2302 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Illegal offset type in /phpbb/ext/phpbbseo/usu/acp/usu.php:156
Stack trace:
#0 /phpbb/includes/functions_module.php(676): phpbbseo\usu\acp\usu->main()
#1 /phpbb/adm/index.php(81): p_master->load_active()
#2 {main}
  thrown in /phpbb/ext/phpbbseo/usu/acp/usu.php on line 156" while reading response header from upstream
```

156 line which is:

``` if (@is_bool($this->core->seo_opt[$optionvalue]))```

**Comment by meis2m** [comment]
https://github.com/phpbb-seo/usu/pull/48
